# Generated by Django 4.2.2 on 2023-07-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_category_options_merch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merches'},
        ),
        migrations.RenameField(
            model_name='merch',
            old_name='sold',
            new_name='is_sold',
        ),
    ]
